project:
  type: book
  preview:
    port: 4300

book:
  title: "issue-references-html-pdf"
  author: "Norah Jones"
  date: "12/14/2025"
  chapters:
    - index.qmd
    - ch01.qmd
    - ch02.qmd

bibliography: references.bib

filters:
  - quarto
  - section-bibliographies


format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt

